### ISSUE TITLE
Overlooked updating dependencies

### ISSUE THREAD

**Issue by marc-vdm** [conda-forge/activity-browser-feedstock#27]
Hi @m-rossi (or @haasad if you know),

It seems I was really dumb earlier today and didn't actually update [meta.yaml](https://github.com/conda-forge/activity-browser-feedstock/blob/d9db453bcb1e7b47e4ac7ea89c9f39a8252fb26d/recipe/meta.yaml#L19) in #25 while I should have updated it to match [our version](https://github.com/LCA-ActivityBrowser/activity-browser/blob/66a02278c63bb8212a3ecb92d945dea0c30dc568/recipe/meta.yaml#L22).

Can I just open a PR here or do we need to make a new release for this to be available on conda-forge?

**Comment by m-rossi** [comment]
Just issue a PR with the updated requirements and bump the build number to `1`
